var data = [
  {
    "name": "冷氣機",
    "english_name": "air conditioner",
    "place": "客廳",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 180,
    "default_consumption": 2200,
    "consumption_mul": 0.65,
    "type": "normal"
  },
  {
    "name": "照明",
    "english_name": "illumination",
    "place": "客廳",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": -1,
    "consumption_mul": 1,
    "type": "light"
  },
  {
    "name": "電視機",
    "english_name": "television",
    "place": "客廳",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": 200,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "機上盒",
    "english_name": "set-top box",
    "place": "客廳",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": 10,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "Wifi分享器",
    "english_name": "wireless router",
    "place": "客廳",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": 10,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "吸塵器",
    "english_name": "vacuum cleaner",
    "place": "客廳",
    "count": 0,
    "rarely": 1,
    "occasionally": 2,
    "often": 3,
    "frequently": 5,
    "day": 365,
    "default_consumption": 1100,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "電風扇",
    "english_name": "electric fan",
    "place": "客廳",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 180,
    "default_consumption": 55,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "音響",
    "english_name": "audio electronics",
    "place": "客廳",
    "count": 0,
    "rarely": 1,
    "occasionally": 3,
    "often": 5,
    "frequently": 8,
    "day": 365,
    "default_consumption": 200,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "DVD光碟機",
    "english_name": "DVD player",
    "place": "客廳",
    "count": 0,
    "rarely": 1,
    "occasionally": 3,
    "often": 5,
    "frequently": 8,
    "day": 365,
    "default_consumption": 30,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "冷氣機",
    "english_name": "air conditioner",
    "place": "臥室",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 180,
    "default_consumption": 2200,
    "consumption_mul": 0.65,
    "type": "normal"
  },
  {
    "name": "照明",
    "english_name": "illumination",
    "place": "臥室",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": -1,
    "consumption_mul": 1,
    "type": "light"
  },
  {
    "name": "電暖器",
    "english_name": "heater",
    "place": "臥室",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 120,
    "default_consumption": 1250,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "電熨斗",
    "english_name": "electric iron",
    "place": "臥室",
    "count": 0,
    "rarely": 1,
    "occasionally": 2,
    "often": 3,
    "frequently": 5,
    "day": 365,
    "default_consumption": 800,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "電腦（桌上型）",
    "english_name": "computer (desktop)",
    "place": "臥室",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": 150,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "電腦（筆記型）",
    "english_name": "notebook",
    "place": "臥室",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": 100,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "印表機",
    "english_name": "printer",
    "place": "臥室",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": 30,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "收音機",
    "english_name": "radio",
    "place": "臥室",
    "count": 0,
    "rarely": 1,
    "occasionally": 3,
    "often": 5,
    "frequently": 8,
    "day": 365,
    "default_consumption": 30,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "除濕機",
    "english_name": "dehumidifier",
    "place": "臥室",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": 200,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "照明",
    "english_name": "illumination",
    "place": "廚房",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": -1,
    "consumption_mul": 1,
    "type": "light"
  },
  {
    "name": "冰箱",
    "english_name": "refrigerator",
    "place": "廚房",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": 200,
    "consumption_mul": 0.55,
    "type": "normal"
  },
  {
    "name": "電熱水瓶",
    "english_name": "electric water boiler",
    "place": "廚房",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": 100,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "電子鍋",
    "english_name": "electronic pot",
    "place": "廚房",
    "count": 0,
    "rarely": 1,
    "occasionally": 3,
    "often": 5,
    "frequently": 8,
    "day": 365,
    "default_consumption": 1000,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "電鍋",
    "english_name": "steam cooker",
    "place": "廚房",
    "count": 0,
    "rarely": 1,
    "occasionally": 3,
    "often": 5,
    "frequently": 8,
    "day": 365,
    "default_consumption": 800,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "飲水機",
    "english_name": "water dispenser",
    "place": "廚房",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": 300,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "烘碗機",
    "english_name": "dish dryer",
    "place": "廚房",
    "count": 0,
    "rarely": 1,
    "occasionally": 3,
    "often": 5,
    "frequently": 8,
    "day": 365,
    "default_consumption": 200,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "微波爐",
    "english_name": "microwave oven",
    "place": "廚房",
    "count": 0,
    "rarely": 1,
    "occasionally": 2,
    "often": 3,
    "frequently": 5,
    "day": 365,
    "default_consumption": 1200,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "電磁爐",
    "english_name": "induction Cooker",
    "place": "廚房",
    "count": 0,
    "rarely": 1,
    "occasionally": 2,
    "often": 3,
    "frequently": 5,
    "day": 365,
    "default_consumption": 1250,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "洗碗機",
    "english_name": "dishwasher",
    "place": "廚房",
    "count": 0,
    "rarely": 1,
    "occasionally": 3,
    "often": 5,
    "frequently": 8,
    "day": 365,
    "default_consumption": 1000,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "抽油煙機",
    "english_name": "range hood",
    "place": "廚房",
    "count": 0,
    "rarely": 1,
    "occasionally": 2,
    "often": 3,
    "frequently": 5,
    "day": 365,
    "default_consumption": 350,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "烤麵包機",
    "english_name": "toaster",
    "place": "廚房",
    "count": 0,
    "rarely": 1,
    "occasionally": 2,
    "often": 3,
    "frequently": 5,
    "day": 365,
    "default_consumption": 800,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "電烤箱",
    "english_name": "electric oven",
    "place": "廚房",
    "count": 0,
    "rarely": 1,
    "occasionally": 2,
    "often": 3,
    "frequently": 5,
    "day": 365,
    "default_consumption": 800,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "照明",
    "english_name": "illumination",
    "place": "浴室",
    "count": 0,
    "rarely": 3,
    "occasionally": 6,
    "often": 18,
    "frequently": 24,
    "day": 365,
    "default_consumption": -1,
    "consumption_mul": 1,
    "type": "light"
  },
  {
    "name": "洗衣機",
    "english_name": "washing machine",
    "place": "浴室",
    "count": 0,
    "rarely": 1,
    "occasionally": 2,
    "often": 3,
    "frequently": 5,
    "day": 365,
    "default_consumption": 500,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "乾衣機",
    "english_name": "drying machine",
    "place": "浴室",
    "count": 0,
    "rarely": 1,
    "occasionally": 2,
    "often": 3,
    "frequently": 5,
    "day": 365,
    "default_consumption": 1200,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "電熱水器",
    "english_name": "water heater",
    "place": "浴室",
    "count": 0,
    "rarely": 2,
    "occasionally": 6,
    "often": 10,
    "frequently": 12,
    "day": 365,
    "default_consumption": -1,
    "consumption_mul": 1,
    "type": "hotwater"
  },
  {
    "name": "吹風機",
    "english_name": "hair dryer",
    "place": "浴室",
    "count": 0,
    "rarely": 1,
    "occasionally": 2,
    "often": 3,
    "frequently": 5,
    "day": 365,
    "default_consumption": 800,
    "consumption_mul": 1,
    "type": "normal"
  },
  {
    "name": "電熨斗",
    "english_name": "electric iron",
    "place": "浴室",
    "count": 0,
    "rarely": 1,
    "occasionally": 2,
    "often": 3,
    "frequently": 5,
    "day": 365,
    "default_consumption": 800,
    "consumption_mul": 1,
    "type": "normal"
  }
];

//載入MySQL模組
var mysql = require('mysql');
//建立連線
var connection = mysql.createConnection({
    host: '127.0.0.1',
    user: 'root',
    password: '@##434frt))',
    database: 'itri2017'
});
//開始連接
connection.connect();
data.forEach(d=>{
    connection.query('INSERT INTO `devices` SET ?', d, function(error){
        if(error){
            console.log('寫入資料失敗！');
            throw error;
        }
    });
})
connection.end();